### ISSUE TITLE
Is this library being updated?

### ISSUE THREAD

**Issue by viperfx** [wildbit/postmark-cli#30]
Hi there, 

This seems like a great tool. Is this being actively maintained by the postmark team?

**Comment by derekrushforth** [comment]
Hey @viperfx! Yep, this tool is actively maintained. Let me know if you have any questions.

**Comment by viperfx** [comment]
Thanks @derekrushforth 

Would love to understand how we can use CSS Frameworks on top of this tool, to develop locally and then push a more compiled and optimised version to postmark. For example, using a framework like Tailwind, or an email framework like https://maizzle.com/

**Comment by derekrushforth** [comment]
Maizzle looks pretty nice. I haven't had a chance to play around with it yet though. If you can modify the folder structure of your compiled templates, you should be able to use our CLI tool with any email framework. Here's an example of the folder structure:

```
src
└── where all your Maizzle source templates sit
dist - Where your compiled templates sit
├── password-reset
│   ├── content.html
│   ├── content.txt
│   └── meta.json
└── welcome
    ├── content.html
    └── meta.json
```

All we require is that each template is in its own folder, the content is named `content.html/txt`, and that a `meta.json` file is there so that Postmark knows what to do with it. Here's an example of the metadata file:
```
{
  "Name": "Receipt",
  "Alias": "receipt",
  "Subject": "Receipt for {{ product_name }}",
  "TemplateType": "Standard",
  "LayoutTemplate": "plain"
}
```

Then from there you can [push your templates](https://github.com/wildbit/postmark-cli/wiki/templates-command#push-templates-directory-options) to Postmark by running `postmark templates push ./dist`. Or see [live previews](https://github.com/wildbit/postmark-cli/wiki/templates-command#preview-templates-directory-options) by running `postmark templates preview ./dist`.

We have an email framework called [MailMason](https://github.com/wildbit/mailmason) that follows this approach.

**Comment by derekrushforth** [comment]
Closing this one for now. Happy to answer any more questions, let me know.
